services:
  app:
    build: .
    container_name: tgBot
    command: ["npm", "start"]
    restart: unless-stopped
    environment:
      - TZ=Europe/Minsk
    env_file:
      - .env
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./logs:/app/logs