services:
  app:
    build: .
    container_name: tgBot
    command: ["node", "bot.js"]
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro